### PR TITLE
doc(glossary): Use definition list with multiple terms

### PR DESCRIPTION
**Pull request by wismill**
This makes the definitions lists clearer and semantically more correct.

(To be rebased on #125)

### CODE REVIEW

**Comment by fabi1cazenave** [comment]
If we feel like the multiple terms for one definition pattern is likely to become common, then I *guess* I’d prefer moving the whole page to HTML right away. But that would sure be a major bummer.

**Comment by wismill** [comment]
If you put this in the first place, I guess that we do have occurrences of these terms here or in useful external resources. So I would prefer to keep the list unchanged than to loose definitions.

I think mixing HTML is ok when there is no Markdown counter part. Consider it “advanced Markdown”.

I find the HTML for DL clearer than the Markdown notation, but I am not strong on this.

**Comment by fabi1cazenave** [comment]
HTML is fine for simple cases, but markdown makes it much easier to handle links and as soon as there are footnotes, HTML doesn’t come close to pandoc markdown imho.

The thing is, AFAIK there’s no way to mix HTML and markdown in a single definition list, which means that for any time that we’d have to use a specific HTML feature we’d have to convert the whole list, thus loosing the git history. Hence, following this path means we should switch everything to HTML as soon as possible.

If it weren’t for these SFU/SKU terms (which we should drop anyway as almost nobody uses them outside of the Ergo‑L team), I might be tempted. But right now this looks like a terrible trade-off to me.

**Comment by wismill** [comment]
Dommage

**Pull request closed without merging**
