### PR TITLE
Cleaner code structure without changing urls.

### PR DESCRIPTION
**Pull request by Nuclear-Squid**
This PR aims to add some order in the code architecture by moving the `bepo`, `erglace` and `lafayette` pages to sub-directories of the `alternatives` page. Urls for those moved pages are kept the same (so the page for erglace is still at `ergol.org/erglace/`, not `ergol.org/alternatives/erglace/`).

I can’t seem to find a reliable way to *completely* build the site locally and kept having problems with pages not being built, which seems to break the menu. The only “““reliable””” way to properly generate the menus (for that section of the site) after a clean build (deleting the `www/public` folder and starting a new `hugo server`) I found was to hit save on `alternatives/index.md`, then `hugo.toml` and finally the 3 child pages *in that particular order*.

If anyone is able to verify that this madness actually work in practice, I would *greatly* appreciate it ! 🚀

### CODE REVIEW

**Comment by Nuclear-Squid** [comment]
All right, I *finally* understood why the build step was so messed up. *Apparently* if a page has children it *has* to be a list (with a `_index.md` name) and cannot be a single page (with a `index.md` name), otherwise the child pages are considered to be resources for the parent page, and not pages of their own. ([source](https://discourse.gohugo.io/t/hugo-does-not-see-or-build-content-unless-change-source-on-disc/21710))

One problem with having the parent page be a list is that summaries of the child pages are appended at the end of the parent page (which we *don’t* want in this context). To fix this, I slightly modified the `layouts/_default/list.html` file to allow not rendering those summaries the custom parameter `hideSummaryOfChildPages` is set to `true` (it’s `false` by default so it doesn’t change the way Hugo renders pages by default, which I feel  would be unhealthy)

Adding Kazé as a reviewer to make sure I didn’t fuck something up (and also because last time I checked he had similar problems)

**Comment by fabi1cazenave** [comment]
LGTM. I’m still unsure whether leaf pages should be named `index.md` or `_index.md` though.

**Comment by Nuclear-Squid** [comment]
I’m guessing they should be named `index.md` to get the `single` page layout. It doesn’t really matter for some pages (like for erglace), but it’s required for articles (since only  `single` pages can render the author or publication date).

**Review by fabi1cazenave — COMMENTED** [review]
Nice work !

**Pull request merged**
