### PR TITLE
Draft: lexique

### PR DESCRIPTION
**Pull request by fabi1cazenave**

### CODE REVIEW

**Comment by fabi1cazenave** [comment]
I hope this is enough for a basic template, so that users can just keep on filling it. As I’m not planning to work on it in the next few days, it would probably be better to merge it so people can contribute to it.

**Comment by wismill** [comment]
> it would probably be better to merge it so people can contribute to it.

Yes, that would help. I think it’s okay to publish it as well, if you clearly state this is a work in progress.

**Comment by Nuclear-Squid** [comment]
Honnestly it’s pretty good as is ! I’d just suggest adding a link to that lexicon in the stats page, as requested in #67. Do you want me to push a commit ?

**Comment by fabi1cazenave** [comment]
Link added. Let’s merge this.

**Pull request merged**
