### PR TITLE
Add progress bar on status message

### PR DESCRIPTION
**Pull request by ClemABT**
A proposal to add progress bar on the status message to better visualize the threshold.

### CODE REVIEW

**Comment by fabi1cazenave** [comment]
Nice and simple. Maybe we could have the same one for the speed target ?

**Comment by ClemABT** [comment]
Which speed target do you mean ? There's actually one progress bar for the CPM and one for the precision.

**Comment by fabi1cazenave** [comment]
I was referring to the 100 cpm speed target, yes — the accuracy target is already covered by your proposal

**Comment by ClemABT** [comment]
The 100 cpm speed target is also covered, I have added 2 progress bar.

**Comment by fabi1cazenave** [comment]
Hahaha sorry, my eye had apply the 80-char cut. Merging.

**Pull request merged**
